matrix:
include:
language:c
sudo:false # only for faster builds
compiler:
 -clang
 -gcc
script:
 - clang -coverage -o0 Chrismustree.c
 -./Chrismustree
 - gcov Chrismustree.c
 - clang -coverage -o0 triangle.c
 -./triangle
 - gcov triangle.c
 - clang -coverage -o0 parellel.c
 -./parellel
 - gcov parellel.c
 - clang -coverage -o0 pattern.c
 -./pattern
 - gcov pattern.c
 hoo#
