matrix:
  include:    
    - language: c  
      sudo: false # only for faster builds  
      compiler:
        - clang
        - gcc
      script:  
        - gcc -o test test.c 
        - ./test
        - gcc -o fact fact.c
        - ./fact
        - gcc -o demo demo.c
        - ./demo
